name: GitHub Repository Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_crawler
        ports:
          - 5432:5432
    
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/github_crawler
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug file presence
        run: |
          ls -la src/
          pwd
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Setup database
        run: python setup_postgres.py
      
      - name: Crawl repositories
        run: python src/crawler.py crawl --target 100000
      
      - name: Export data
        run: python src/crawler.py export --output repositories.csv
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-data
          path: repositories.csv
