name: GitHub Repository Crawler

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: crawlerdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Postgres schema
        run: python setup_postgres.py
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: crawlerdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432

      - name: Crawl GitHub repos
        run: python src/crawler.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTGRES_HOST: localhost
          POSTGRES_DB: crawlerdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432

      - name: Dump database to CSV
        run: |
          pg_dump -h localhost -U postgres -d crawlerdb --data-only --column-inserts > dump.sql
          PGPASSWORD=postgres psql -h localhost -U postgres -d crawlerdb -c "\COPY repositories TO 'repositories.csv' CSV HEADER"
        env:
          PGPASSWORD: postgres

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: repository-data
          path: repositories.csv
